%YAML:1.2
# SPDX-FileCopyrightText: 2021 Smart Robotics Lab, Imperial College London, Technical University of Munich
# SPDX-License-Identifier: CC0-1.0

general:
  # outputs
  results_directory:          "/home/"
  write_mesh_output: true

  # Sensor processing
  sensor_measurement_downsampling: 1
  depth_image_resolution_downsampling: 2

  # Submapping
  submap_kf_threshold: 1 # not really used at the moment
  submap_overlap_ratio: 0.4 # 0.3
  submap_min_frames: 40 # 100

  # Alignment settings
  use_map_to_map_factors: true
  use_map_to_live_factors: true
  n_factors_per_state: 100 # number of points per depth images
  voxel_grid_resolution: 0.06
  sensor_error: 0.01 # 1-sigma for obsv. noise [m]

  # Near and Far Plane
  near_plane: 0.6
  far_plane: 30.0

map:
  dim:                        [15.36, 15.36, 15.36]
  res:                        0.03

data:
  # occupancy
  surface_boundary:           0
  min_occupancy:              -100
  max_occupancy:               100
  log_odd_min:                -5.015
  log_odd_max:                 5.015
  fs_integr_scale:            1
  const_surface_thickness:    false
  uncertainty_model:          linear
  tau_min_factor:             3
  tau_max_factor:             12
  k_tau:                      0.05
  sigma_min_factor:           1         # minimum/maximum uncertainty := 3 x sigma_min_factor/sigma_max_factor * voxel_dim
  sigma_max_factor:           3         # minimum/maximum uncertainty := 3 x sigma_min_factor/sigma_max_factor * voxel_dim
  k_sigma:                    0.05