%YAML:1.2
# SPDX-FileCopyrightText: 2021-2023 Smart Robotics Lab, Imperial College London, Technical University of Munich
# SPDX-License-Identifier: CC0-1.0

general:
  # outputs
  results_directory:          "/home/"
  write_mesh_output: true

  # Sensor processing
  sensor_measurement_downsampling: 2
  depth_image_resolution_downsampling: 2

  # Submapping
  submap_kf_threshold: 20
  submap_overlap_ratio: 0.1
  submap_min_frames: 60 # for hand-held sequences
  near_plane: 0.4
  far_plane: 10.0 # stereo baseline is 0.5m

  # Alignment settings
  use_map_to_map_factors: true
  use_map_to_live_factors: true
  n_factors_per_state: 200 # number of points per depth images
  sensor_error: 0.4 # 1-sigma for obsv. noise [m]

  # Network depth settings
  use_uncertainty: true


map:
  dim:            [51.2, 51.2, 51.2]  # for hand-held sequences
  res:            0.2

data:
  # occupancy data
  surface_boundary:        0
  min_occupancy:           -100
  max_occupancy:            100
  log_odd_min:             -5.015
  log_odd_max:              5.015
  fs_integr_scale:         1
  const_surface_thickness: false
  uncertainty_model:       quadratic
  tau_min_factor:          3
  tau_max_factor:          12
  k_tau:                   0.2
  sigma_min_factor:        1      # minimum/maximum uncertainty := 3 x sigma_min_factor/sigma_max_factor * voxel_dim
  sigma_max_factor:        20     # minimum/maximum uncertainty := 3 x sigma_min_factor/sigma_max_factor * voxel_dim
  k_sigma:                 0.05